### ISSUE TITLE
syntax error when trying to import

### ISSUE THREAD

**Issue by glasswalk3r** [allisson/python-simple-rest-client#4]
Just installed python-simple-rest-client by using pip inside a virtualenv and tried the following:

```
(venv) [alceu@localhost harbor-cleanup]$ python
Python 3.4.5 (default, Dec 11 2017, 14:22:24) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-16)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from simple_rest_client.api import API
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/alceu/Projetos/harbor-cleanup/venv/lib/python3.4/site-packages/simple_rest_client/api.py", line 1, in <module>
    from .resource import Resource
  File "/home/alceu/Projetos/harbor-cleanup/venv/lib/python3.4/site-packages/simple_rest_client/resource.py", line 119
    async def action_method(self, *args, body=None, params=None,
            ^
SyntaxError: invalid syntax
>>> 
```

I'm using Python 3.4.5 and Virtualenv 15.1.0.

**Comment by allisson** [comment]
Hello @glasswalk3r, this lib requires python >= 3.5 :+1:
